### PR TITLE
Quote paths

### PR DESCRIPTION
**Pull request by lpinner**
Related to issue 16.  Have not looked at conda-wrappers-feedstock but looks like you done some work there already in [21ae7ad6552b2f81fbce9a9646d30b490bc1b369](https://github.com/conda-forge/conda-wrappers-feedstock/pull/5/commits/21ae7ad6552b2f81fbce9a9646d30b490bc1b369)

### CODE REVIEW

**Comment by gqmelo** [comment]
Thanks @lpinner . Could you just undo the changes on ```post-link.bat```? This file is no longer used. It's from the recipe that now lives on conda-forge (which I fixed and should merge soon).

I actually removed the recipe on another branch where I'm doing some clean up

**Comment by lpinner** [comment]
@gqmelo Will do tomorrow

**Comment by gqmelo** [comment]
I see the build is failing and post-link.bat is still changed. But if you don't mind I'll cherry pick your commits and fix it. I have a branch I want to merge with lots of changes that will probably cause conflicts with yours. And I wouldn't like to make you solve those conflicts :P

**Comment by gqmelo** [comment]
Done
The commit is already on master: https://github.com/gqmelo/exec-wrappers/commit/a9b56fa6ee6588a4cd10fa8384600755c5ff0d71

Thanks

**Pull request closed without merging**
